server:
  port: 9001
spring:
  application:
    name: uac
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
security:
  oauth2:
#    client:
#      clientId: app1
#      clientSecret: 123456
#      access-token-uri: http://localhost:9000/oauth/token
#      user-authorization-uri: http://localhost:9000/oauth/authorize
    resource:
      user-info-uri: http://localhost:9000/user
      prefer-token-info: false