server:
  port: 8000
spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    oauth-center-route:
      path: /oauth-center/**
      sensitiveHeaders:
      service-id: OAUTH2-AUTHORIZATION-SERVER
    uac-route:
      path: /uac/**
      sensitiveHeaders:
      service-id: UAC
    order-route:
      path: /order/**
      sensitiveHeaders:
      service-id: ORDER
    cookie-demo:
      path: /cookie/**
      sensitiveHeaders:
      service-id: COOKIE-DEMO
  add-proxy-headers: true
security:
  oauth2:
    client:
      clientId: app1
      clientSecret: 123456
      access-token-uri: http://localhost:8000/oauth-center/oauth/token
      user-authorization-uri: http://localhost:8000/oauth-center/oauth/authorize
    resource:
      user-info-uri: http://localhost:8000/oauth-center/user
      prefer-token-info: false
logging:
  level: debug