server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
security:
  basic:
    enabled: true
  user:
    name: root
    password: root
spring:
  application:
    name: eureka-server