server:
  port: 9000
spring:
  application:
    name: oauth2-authorization-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#security:
#  user:
#    name: root
#    password: root
#  basic:
#    enabled: false
security:
  oauth2:
    client:
      clientId: app1
      clientSecret: 123456
      access-token-uri: http://localhost:8000/oauth-center/oauth/token
      user-authorization-uri: http://localhost:8000/oauth-center/oauth/authorize
    resource:
      user-info-uri: http://localhost:8000/oauth-center/user
      prefer-token-info: false